application:
  name: api
  project: url-shortener
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11.5"
    name: my-pql-db
routers:
  - name: main
    routes:
      - application_name: api
        paths:
          - /*