application:
  name: "URLShortener"
databases:
- type: "POSTGRESQL"
  name: "URLShortener-hm"
  version: "11"
routers:
- name: "main-URLShortener"
  routes:
  - application_name: "URLShortener"
    paths:
    - "/*"
