---
application:
  name: "urlshortener"
  project: "URLShortener"
  organization: "QoveryCommunity"
routers:
- name: "main-urlshortener"
  routes:
  - application_name: "urlshortener"
    paths:
    - "/*"
