---
application:
  name: "api"
  project: "URLShortener"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "URLShortener"
  version: "11"
routers:
- name: "main-api"
  routes:
  - application_name: "api"
    paths:
    - "/*"
