application:
  name: URLShortener
  project: URLShortener
  publicly_accessible: true
databases:
- type: postgresql
  version: "11"
  name: URLShortener
routers:
- name: main
  routes:
  - application_name: api
    paths:
    - /*
